**Activity 7**

A palindrome is a string which is same read forward or backwards.

For example: "dad" is the same in forward or reverse direction. Another example is "aibohphobia" which literally means, an irritable fear of palindromes.

Write a function in python that receives a string and returns True if that string is a palindrome and False otherwise. Remember that difference between upper and lower case characters are ignored during this determination.

In [6]:
def isPalindrome(word):
  temp=word[::-1]
  if temp.capitalize()==word.capitalize():
    return True
  else:
    return False

In [7]:
print(isPalindrome('malayalam'))
print(isPalindrome('dedo'))
print(isPalindrome('maam'))
print(isPalindrome('geeks'))
print(isPalindrome('deed'))

True
False
True
False
True

**Activity 8**

Imagine two matrices given in the form of 2D lists as under;

a = [[1, 0, 0], [0, 1, 0], [0, 0, 1] ]

b = [[1, 2, 3], [4, 5, 6], [7, 8, 9] ]

Write a python code that finds another matrix/2D list that is a product of and b, i.e.,
C=a*b

In [8]:
a=[[1,0,0],[0,1,0],[0,0,1]]
b=[[1,2,3],[4,5,6],[7,8,9]]
c=[]

for indrow in range(3):
  c.append([])
  for indcol in range(3):
    c[indrow].append(0)
    for indaux in range(3):
      c[indrow][indcol]+=a[indrow][indaux]*b[indcol][indaux]
print(c)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

**Activity 9**

A closed polygon with N sides can be represented as a list of tuples of N connected coordinates, 

i.e., [ (x1,y1), (x2,y2), (x3,y3), . . . , (xN,yN) ]. A sample polygon with 6 sides (N=6) is shown below.

Write a python function that takes a list of N tuples as input and returns the perimeter of the 
polygon. Remember that your code should work for any value of N.

![image.png]()

In [9]:
def perimeter(listing):
  leng=len(listing)
  print(leng)
  perimeter=0
  for i in range(0,leng-1):
    print("The leng of 'leng-1' is",leng-1)
    print("Value of i",i)
    dist=(((listing[i][0]-listing[i+1][0])**2)+((listing[i][1]-listing[i+1][1])**2))**0.5
    perimeter=perimeter+dist
  perimeter=perimeter+ (((listing[0][0]-listing[leng-1][0])**2)+((listing[0][1]-listing[leng-1][1])**2))**0.5
  return perimeter

In [10]:
L=[(1,3),(2,7),(3,9),(-1,8)]
print(perimeter(L))

4
The leng of 'leng-1' is 3
Value of i 0
The leng of 'leng-1' is 3
Value of i 1
The leng of 'leng-1' is 3
Value of i 2
15.867444035869614

**Activity 10**

Imagine two sets A and B containing numbers. Without using built-in set functionalities, write your own function that receives two such sets and returns another set C which is a symmetric difference of the two input sets. 

(A symmetric difference between A and B will 
return a set C which contains only those items that appear in one of A or B. Any items that 
appear in both sets are not included in C). 

Now compare the output of your function with the 
following built-in functions/operators.

 A.symmetric_difference(B)

 B.symmetric_difference(A)

 A ^ B

 B ^ A

In [11]:
def symmDiff(a,b):
  e=set()
  for i in a:
    if i not in b:
      e.add(i)
  for i in b:
    if i not in a:
      e.add(i)
  return e

In [12]:
set1={0,1,2,4,5}
set2={4,5,7,8,9}
print(symmDiff(set1,set2))
print(set1^set2)
print(set2^set1)

{0, 1, 2, 7, 8, 9}
{0, 1, 2, 7, 8, 9}
{0, 1, 2, 7, 8, 9}

**Assignment**

![image.png]()


This code first creates a list x that goes from -pi to pi with an increment of 0.001. It then loops over each value in x, computes the approximate derivative using the given formula, and compares it with the exact derivative computed using the cos function. The results are printed out for each point.

If we increase the value of h from 0.001 to 0.01 and then to 0.1, we are using larger increments for the approximation. As a result, the accuracy of the approximation decreases and the error between the approximate and exact derivatives increases. We can observe this by running the above code with different values of h.

In [13]:
from math import sin, cos, pi

x = [-pi + i*0.001 for i in range(int(2*pi/0.001)+1)]
print("Values of X are",x)
hs = [0.001, 0.01, 0.1]

for h in hs:
    print(f"The vaule of h is = {h}")
    for i in range(len(x)):
        df_sin = (sin(x[i]+h) - sin(x[i]))/h
        df_cos = cos(x[i])
        if (df_sin==df_cos):
           print("df_sin is equal to df_cos")
        else:
          print("df_sin is not equal to df_cos")
           # difference = abs(df_sin - df_cos)
        print(f"value of x = {x[i]:.5f}\tSin x value is: {df_sin:.5f}\t Cos x value : {df_cos:.5f}")
              # \t : {error:.5f}")

Streaming output truncated to the last 5000 lines.
df_sin is not equal to df_cos
value of x = 0.64241	Sin x value is: 0.76939	 Cos x value : 0.80066
df_sin is not equal to df_cos
value of x = 0.64341	Sin x value is: 0.76875	 Cos x value : 0.80006
df_sin is not equal to df_cos
value of x = 0.64441	Sin x value is: 0.76811	 Cos x value : 0.79946
df_sin is not equal to df_cos
value of x = 0.64541	Sin x value is: 0.76747	 Cos x value : 0.79885
df_sin is not equal to df_cos
value of x = 0.64641	Sin x value is: 0.76683	 Cos x value : 0.79825
df_sin is not equal to df_cos
value of x = 0.64741	Sin x value is: 0.76619	 Cos x value : 0.79765
df_sin is not equal to df_cos
value of x = 0.64841	Sin x value is: 0.76555	 Cos x value : 0.79705
df_sin is not equal to df_cos
value of x = 0.64941	Sin x value is: 0.76491	 Cos x value : 0.79644
df_sin is not equal to df_cos
value of x = 0.65041	Sin x value is: 0.76426	 Cos x value : 0.79584
df_sin is not equal to df_cos
value of x = 0.65141	Sin x value is: 0.76362	 Cos x value : 0.79523
df_sin is not equal to df_cos
value of x = 0.65241	Sin x value is: 0.76297	 Cos x value : 0.79462
df_sin is not equal to df_cos
value of x = 0.65341	Sin x value is: 0.76232	 Cos x value : 0.79402
df_sin is not equal to df_cos
value of x = 0.65441	Sin x value is: 0.76168	 Cos x value : 0.79341
df_sin is not equal to df_cos
value of x = 0.65541	Sin x value is: 0.76103	 Cos x value : 0.79280
df_sin is not equal to df_cos
value of x = 0.65641	Sin x value is: 0.76038	 Cos x value : 0.79219
df_sin is not equal to df_cos
value of x = 0.65741	Sin x value is: 0.75973	 Cos x value : 0.79158
df_sin is not equal to df_cos
value of x = 0.65841	Sin x value is: 0.75908	 Cos x value : 0.79097
df_sin is not equal to df_cos
value of x = 0.65941	Sin x value is: 0.75843	 Cos x value : 0.79036
df_sin is not equal to df_cos
value of x = 0.66041	Sin x value is: 0.75778	 Cos x value : 0.78974
df_sin is not equal to df_cos
value of x = 0.66141	Sin x value is: 0.75713	 Cos x value : 0.78913
df_sin is not equal to df_cos
value of x = 0.66241	Sin x value is: 0.75648	 Cos x value : 0.78851
df_sin is not equal to df_cos
value of x = 0.66341	Sin x value is: 0.75582	 Cos x value : 0.78790
df_sin is not equal to df_cos
value of x = 0.66441	Sin x value is: 0.75517	 Cos x value : 0.78728
df_sin is not equal to df_cos
value of x = 0.66541	Sin x value is: 0.75451	 Cos x value : 0.78667
df_sin is not equal to df_cos
value of x = 0.66641	Sin x value is: 0.75386	 Cos x value : 0.78605
df_sin is not equal to df_cos
value of x = 0.66741	Sin x value is: 0.75320	 Cos x value : 0.78543
df_sin is not equal to df_cos
value of x = 0.66841	Sin x value is: 0.75254	 Cos x value : 0.78481
df_sin is not equal to df_cos
value of x = 0.66941	Sin x value is: 0.75188	 Cos x value : 0.78419
df_sin is not equal to df_cos
value of x = 0.67041	Sin x value is: 0.75122	 Cos x value : 0.78357
df_sin is not equal to df_cos
value of x = 0.67141	Sin x value is: 0.75056	 Cos x value : 0.78295
df_sin is not equal to df_cos
value of x = 0.67241	Sin x value is: 0.74990	 Cos x value : 0.78232
df_sin is not equal to df_cos
value of x = 0.67341	Sin x value is: 0.74924	 Cos x value : 0.78170
df_sin is not equal to df_cos
value of x = 0.67441	Sin x value is: 0.74858	 Cos x value : 0.78108
df_sin is not equal to df_cos
value of x = 0.67541	Sin x value is: 0.74792	 Cos x value : 0.78045
df_sin is not equal to df_cos
value of x = 0.67641	Sin x value is: 0.74725	 Cos x value : 0.77983
df_sin is not equal to df_cos
value of x = 0.67741	Sin x value is: 0.74659	 Cos x value : 0.77920
df_sin is not equal to df_cos
value of x = 0.67841	Sin x value is: 0.74592	 Cos x value : 0.77857
df_sin is not equal to df_cos
value of x = 0.67941	Sin x value is: 0.74526	 Cos x value : 0.77795
df_sin is not equal to df_cos
value of x = 0.68041	Sin x value is: 0.74459	 Cos x value : 0.77732
df_sin is not equal to df_cos
value of x = 0.68141	Sin x value is: 0.74393	 Cos x value : 0.77669
df_sin is not equal to df_cos
value of x = 0.68241	Sin x value is: 0.74326	 Cos x value : 0.77606
df_sin is not equal to df_cos
value of x = 0.68341	Sin x value is: 0.74259	 Cos x value : 0.77543
df_sin is not equal to df_cos
value of x = 0.68441	Sin x value is: 0.74192	 Cos x value : 0.77479
df_sin is not equal to df_cos
value of x = 0.68541	Sin x value is: 0.74125	 Cos x value : 0.77416
df_sin is not equal to df_cos
value of x = 0.68641	Sin x value is: 0.74058	 Cos x value : 0.77353
df_sin is not equal to df_cos
value of x = 0.68741	Sin x value is: 0.73991	 Cos x value : 0.77289
df_sin is not equal to df_cos
value of x = 0.68841	Sin x value is: 0.73923	 Cos x value : 0.77226
df_sin is not equal to df_cos
value of x = 0.68941	Sin x value is: 0.73856	 Cos x value : 0.77162
df_sin is not equal to df_cos
value of x = 0.69041	Sin x value is: 0.73789	 Cos x value : 0.77099
df_sin is not equal to df_cos
value of x = 0.69141	Sin x value is: 0.73721	 Cos x value : 0.77035
df_sin is not equal to df_cos
value of x = 0.69241	Sin x value is: 0.73654	 Cos x value : 0.76971
df_sin is not equal to df_cos
value of x = 0.69341	Sin x value is: 0.73586	 Cos x value : 0.76907
df_sin is not equal to df_cos
value of x = 0.69441	Sin x value is: 0.73518	 Cos x value : 0.76843
df_sin is not equal to df_cos
value of x = 0.69541	Sin x value is: 0.73451	 Cos x value : 0.76779
df_sin is not equal to df_cos
value of x = 0.69641	Sin x value is: 0.73383	 Cos x value : 0.76715
df_sin is not equal to df_cos
value of x = 0.69741	Sin x value is: 0.73315	 Cos x value : 0.76651
df_sin is not equal to df_cos
value of x = 0.69841	Sin x value is: 0.73247	 Cos x value : 0.76587
df_sin is not equal to df_cos
value of x = 0.69941	Sin x value is: 0.73179	 Cos x value : 0.76522
df_sin is not equal to df_cos
value of x = 0.70041	Sin x value is: 0.73111	 Cos x value : 0.76458
df_sin is not equal to df_cos
value of x = 0.70141	Sin x value is: 0.73042	 Cos x value : 0.76393
df_sin is not equal to df_cos
value of x = 0.70241	Sin x value is: 0.72974	 Cos x value : 0.76329
df_sin is not equal to df_cos
value of x = 0.70341	Sin x value is: 0.72906	 Cos x value : 0.76264
df_sin is not equal to df_cos
value of x = 0.70441	Sin x value is: 0.72837	 Cos x value : 0.76200
df_sin is not equal to df_cos
value of x = 0.70541	Sin x value is: 0.72769	 Cos x value : 0.76135
df_sin is not equal to df_cos
value of x = 0.70641	Sin x value is: 0.72700	 Cos x value : 0.76070
df_sin is not equal to df_cos
value of x = 0.70741	Sin x value is: 0.72632	 Cos x value : 0.76005
df_sin is not equal to df_cos
value of x = 0.70841	Sin x value is: 0.72563	 Cos x value : 0.75940
df_sin is not equal to df_cos
value of x = 0.70941	Sin x value is: 0.72494	 Cos x value : 0.75875
df_sin is not equal to df_cos
value of x = 0.71041	Sin x value is: 0.72425	 Cos x value : 0.75810
df_sin is not equal to df_cos
value of x = 0.71141	Sin x value is: 0.72356	 Cos x value : 0.75744
df_sin is not equal to df_cos
value of x = 0.71241	Sin x value is: 0.72287	 Cos x value : 0.75679
df_sin is not equal to df_cos
value of x = 0.71341	Sin x value is: 0.72218	 Cos x value : 0.75614
df_sin is not equal to df_cos
value of x = 0.71441	Sin x value is: 0.72149	 Cos x value : 0.75548
df_sin is not equal to df_cos
value of x = 0.71541	Sin x value is: 0.72080	 Cos x value : 0.75483
df_sin is not equal to df_cos
value of x = 0.71641	Sin x value is: 0.72011	 Cos x value : 0.75417
df_sin is not equal to df_cos
value of x = 0.71741	Sin x value is: 0.71941	 Cos x value : 0.75351
df_sin is not equal to df_cos
value of x = 0.71841	Sin x value is: 0.71872	 Cos x value : 0.75285
df_sin is not equal to df_cos
value of x = 0.71941	Sin x value is: 0.71802	 Cos x value : 0.75220
df_sin is not equal to df_cos
value of x = 0.72041	Sin x value is: 0.71733	 Cos x value : 0.75154
df_sin is not equal to df_cos
value of x = 0.72141	Sin x value is: 0.71663	 Cos x value : 0.75088
df_sin is not equal to df_cos
value of x = 0.72241	Sin x value is: 0.71593	 Cos x value : 0.75022
df_sin is not equal to df_cos
value of x = 0.72341	Sin x value is: 0.71524	 Cos x value : 0.74955
df_sin is not equal to df_cos
value of x = 0.72441	Sin x value is: 0.71454	 Cos x value : 0.74889
df_sin is not equal to df_cos
value of x = 0.72541	Sin x value is: 0.71384	 Cos x value : 0.74823
df_sin is not equal to df_cos
value of x = 0.72641	Sin x value is: 0.71314	 Cos x value : 0.74757
df_sin is not equal to df_cos
value of x = 0.72741	Sin x value is: 0.71244	 Cos x value : 0.74690
df_sin is not equal to df_cos
value of x = 0.72841	Sin x value is: 0.71174	 Cos x value : 0.74624
df_sin is not equal to df_cos
value of x = 0.72941	Sin x value is: 0.71103	 Cos x value : 0.74557
df_sin is not equal to df_cos
value of x = 0.73041	Sin x value is: 0.71033	 Cos x value : 0.74490
df_sin is not equal to df_cos
value of x = 0.73141	Sin x value is: 0.70963	 Cos x value : 0.74424
df_sin is not equal to df_cos
value of x = 0.73241	Sin x value is: 0.70892	 Cos x value : 0.74357
df_sin is not equal to df_cos
value of x = 0.73341	Sin x value is: 0.70822	 Cos x value : 0.74290
df_sin is not equal to df_cos
value of x = 0.73441	Sin x value is: 0.70751	 Cos x value : 0.74223
df_sin is not equal to df_cos
value of x = 0.73541	Sin x value is: 0.70681	 Cos x value : 0.74156
df_sin is not equal to df_cos
value of x = 0.73641	Sin x value is: 0.70610	 Cos x value : 0.74089
df_sin is not equal to df_cos
value of x = 0.73741	Sin x value is: 0.70539	 Cos x value : 0.74021
df_sin is not equal to df_cos
value of x = 0.73841	Sin x value is: 0.70468	 Cos x value : 0.73954
df_sin is not equal to df_cos
value of x = 0.73941	Sin x value is: 0.70397	 Cos x value : 0.73887
df_sin is not equal to df_cos
value of x = 0.74041	Sin x value is: 0.70326	 Cos x value : 0.73819
df_sin is not equal to df_cos
value of x = 0.74141	Sin x value is: 0.70255	 Cos x value : 0.73752
df_sin is not equal to df_cos
value of x = 0.74241	Sin x value is: 0.70184	 Cos x value : 0.73684
df_sin is not equal to df_cos
value of x = 0.74341	Sin x value is: 0.70113	 Cos x value : 0.73617
df_sin is not equal to df_cos
value of x = 0.74441	Sin x value is: 0.70042	 Cos x value : 0.73549
df_sin is not equal to df_cos
value of x = 0.74541	Sin x value is: 0.69970	 Cos x value : 0.73481
df_sin is not equal to df_cos
value of x = 0.74641	Sin x value is: 0.69899	 Cos x value : 0.73413
df_sin is not equal to df_cos
value of x = 0.74741	Sin x value is: 0.69827	 Cos x value : 0.73345
df_sin is not equal to df_cos
value of x = 0.74841	Sin x value is: 0.69756	 Cos x value : 0.73277
df_sin is not equal to df_cos
value of x = 0.74941	Sin x value is: 0.69684	 Cos x value : 0.73209
df_sin is not equal to df_cos
value of x = 0.75041	Sin x value is: 0.69612	 Cos x value : 0.73141
df_sin is not equal to df_cos
value of x = 0.75141	Sin x value is: 0.69541	 Cos x value : 0.73073
df_sin is not equal to df_cos
value of x = 0.75241	Sin x value is: 0.69469	 Cos x value : 0.73005
df_sin is not equal to df_cos
value of x = 0.75341	Sin x value is: 0.69397	 Cos x value : 0.72936
df_sin is not equal to df_cos
value of x = 0.75441	Sin x value is: 0.69325	 Cos x value : 0.72868
df_sin is not equal to df_cos
value of x = 0.75541	Sin x value is: 0.69253	 Cos x value : 0.72799
df_sin is not equal to df_cos
value of x = 0.75641	Sin x value is: 0.69181	 Cos x value : 0.72731
df_sin is not equal to df_cos
value of x = 0.75741	Sin x value is: 0.69109	 Cos x value : 0.72662
df_sin is not equal to df_cos
value of x = 0.75841	Sin x value is: 0.69036	 Cos x value : 0.72593
df_sin is not equal to df_cos
value of x = 0.75941	Sin x value is: 0.68964	 Cos x value : 0.72524
df_sin is not equal to df_cos
value of x = 0.76041	Sin x value is: 0.68892	 Cos x value : 0.72456
df_sin is not equal to df_cos
value of x = 0.76141	Sin x value is: 0.68819	 Cos x value : 0.72387
df_sin is not equal to df_cos
value of x = 0.76241	Sin x value is: 0.68747	 Cos x value : 0.72318
df_sin is not equal to df_cos
value of x = 0.76341	Sin x value is: 0.68674	 Cos x value : 0.72248
df_sin is not equal to df_cos
value of x = 0.76441	Sin x value is: 0.68601	 Cos x value : 0.72179
df_sin is not equal to df_cos
value of x = 0.76541	Sin x value is: 0.68529	 Cos x value : 0.72110
df_sin is not equal to df_cos
value of x = 0.76641	Sin x value is: 0.68456	 Cos x value : 0.72041
df_sin is not equal to df_cos
value of x = 0.76741	Sin x value is: 0.68383	 Cos x value : 0.71971
df_sin is not equal to df_cos
value of x = 0.76841	Sin x value is: 0.68310	 Cos x value : 0.71902
df_sin is not equal to df_cos
value of x = 0.76941	Sin x value is: 0.68237	 Cos x value : 0.71832
df_sin is not equal to df_cos
value of x = 0.77041	Sin x value is: 0.68164	 Cos x value : 0.71763
df_sin is not equal to df_cos
value of x = 0.77141	Sin x value is: 0.68091	 Cos x value : 0.71693
df_sin is not equal to df_cos
value of x = 0.77241	Sin x value is: 0.68018	 Cos x value : 0.71623
df_sin is not equal to df_cos
value of x = 0.77341	Sin x value is: 0.67944	 Cos x value : 0.71553
df_sin is not equal to df_cos
value of x = 0.77441	Sin x value is: 0.67871	 Cos x value : 0.71484
df_sin is not equal to df_cos
value of x = 0.77541	Sin x value is: 0.67798	 Cos x value : 0.71414
df_sin is not equal to df_cos
value of x = 0.77641	Sin x value is: 0.67724	 Cos x value : 0.71344
df_sin is not equal to df_cos
value of x = 0.77741	Sin x value is: 0.67650	 Cos x value : 0.71273
df_sin is not equal to df_cos
value of x = 0.77841	Sin x value is: 0.67577	 Cos x value : 0.71203
df_sin is not equal to df_cos
value of x = 0.77941	Sin x value is: 0.67503	 Cos x value : 0.71133
df_sin is not equal to df_cos
value of x = 0.78041	Sin x value is: 0.67429	 Cos x value : 0.71063
df_sin is not equal to df_cos
value of x = 0.78141	Sin x value is: 0.67356	 Cos x value : 0.70992
df_sin is not equal to df_cos
value of x = 0.78241	Sin x value is: 0.67282	 Cos x value : 0.70922
df_sin is not equal to df_cos
value of x = 0.78341	Sin x value is: 0.67208	 Cos x value : 0.70851
df_sin is not equal to df_cos
value of x = 0.78441	Sin x value is: 0.67134	 Cos x value : 0.70781
df_sin is not equal to df_cos
value of x = 0.78541	Sin x value is: 0.67060	 Cos x value : 0.70710
df_sin is not equal to df_cos
value of x = 0.78641	Sin x value is: 0.66985	 Cos x value : 0.70639
df_sin is not equal to df_cos
value of x = 0.78741	Sin x value is: 0.66911	 Cos x value : 0.70568
df_sin is not equal to df_cos
value of x = 0.78841	Sin x value is: 0.66837	 Cos x value : 0.70498
df_sin is not equal to df_cos
value of x = 0.78941	Sin x value is: 0.66763	 Cos x value : 0.70427
df_sin is not equal to df_cos
value of x = 0.79041	Sin x value is: 0.66688	 Cos x value : 0.70356
df_sin is not equal to df_cos
value of x = 0.79141	Sin x value is: 0.66614	 Cos x value : 0.70284
df_sin is not equal to df_cos
value of x = 0.79241	Sin x value is: 0.66539	 Cos x value : 0.70213
df_sin is not equal to df_cos
value of x = 0.79341	Sin x value is: 0.66464	 Cos x value : 0.70142
df_sin is not equal to df_cos
value of x = 0.79441	Sin x value is: 0.66390	 Cos x value : 0.70071
df_sin is not equal to df_cos
value of x = 0.79541	Sin x value is: 0.66315	 Cos x value : 0.69999
df_sin is not equal to df_cos
value of x = 0.79641	Sin x value is: 0.66240	 Cos x value : 0.69928
df_sin is not equal to df_cos
value of x = 0.79741	Sin x value is: 0.66165	 Cos x value : 0.69856
df_sin is not equal to df_cos
value of x = 0.79841	Sin x value is: 0.66090	 Cos x value : 0.69785
df_sin is not equal to df_cos
value of x = 0.79941	Sin x value is: 0.66015	 Cos x value : 0.69713
df_sin is not equal to df_cos
value of x = 0.80041	Sin x value is: 0.65940	 Cos x value : 0.69641
df_sin is not equal to df_cos
value of x = 0.80141	Sin x value is: 0.65865	 Cos x value : 0.69570
df_sin is not equal to df_cos
value of x = 0.80241	Sin x value is: 0.65790	 Cos x value : 0.69498
df_sin is not equal to df_cos
value of x = 0.80341	Sin x value is: 0.65715	 Cos x value : 0.69426
df_sin is not equal to df_cos
value of x = 0.80441	Sin x value is: 0.65639	 Cos x value : 0.69354
df_sin is not equal to df_cos
value of x = 0.80541	Sin x value is: 0.65564	 Cos x value : 0.69282
df_sin is not equal to df_cos
value of x = 0.80641	Sin x value is: 0.65488	 Cos x value : 0.69210
df_sin is not equal to df_cos
value of x = 0.80741	Sin x value is: 0.65413	 Cos x value : 0.69137
df_sin is not equal to df_cos
value of x = 0.80841	Sin x value is: 0.65337	 Cos x value : 0.69065
df_sin is not equal to df_cos
value of x = 0.80941	Sin x value is: 0.65261	 Cos x value : 0.68993
df_sin is not equal to df_cos
value of x = 0.81041	Sin x value is: 0.65186	 Cos x value : 0.68920
df_sin is not equal to df_cos
value of x = 0.81141	Sin x value is: 0.65110	 Cos x value : 0.68848
df_sin is not equal to df_cos
value of x = 0.81241	Sin x value is: 0.65034	 Cos x value : 0.68775
df_sin is not equal to df_cos
value of x = 0.81341	Sin x value is: 0.64958	 Cos x value : 0.68703
df_sin is not equal to df_cos
value of x = 0.81441	Sin x value is: 0.64882	 Cos x value : 0.68630
df_sin is not equal to df_cos
value of x = 0.81541	Sin x value is: 0.64806	 Cos x value : 0.68557
df_sin is not equal to df_cos
value of x = 0.81641	Sin x value is: 0.64730	 Cos x value : 0.68484
df_sin is not equal to df_cos
value of x = 0.81741	Sin x value is: 0.64654	 Cos x value : 0.68411
df_sin is not equal to df_cos
value of x = 0.81841	Sin x value is: 0.64577	 Cos x value : 0.68338
df_sin is not equal to df_cos
value of x = 0.81941	Sin x value is: 0.64501	 Cos x value : 0.68265
df_sin is not equal to df_cos
value of x = 0.82041	Sin x value is: 0.64425	 Cos x value : 0.68192
df_sin is not equal to df_cos
value of x = 0.82141	Sin x value is: 0.64348	 Cos x value : 0.68119
df_sin is not equal to df_cos
value of x = 0.82241	Sin x value is: 0.64272	 Cos x value : 0.68046
df_sin is not equal to df_cos
value of x = 0.82341	Sin x value is: 0.64195	 Cos x value : 0.67973
df_sin is not equal to df_cos
value of x = 0.82441	Sin x value is: 0.64118	 Cos x value : 0.67899
df_sin is not equal to df_cos
value of x = 0.82541	Sin x value is: 0.64042	 Cos x value : 0.67826
df_sin is not equal to df_cos
value of x = 0.82641	Sin x value is: 0.63965	 Cos x value : 0.67752
df_sin is not equal to df_cos
value of x = 0.82741	Sin x value is: 0.63888	 Cos x value : 0.67679
df_sin is not equal to df_cos
value of x = 0.82841	Sin x value is: 0.63811	 Cos x value : 0.67605
df_sin is not equal to df_cos
value of x = 0.82941	Sin x value is: 0.63734	 Cos x value : 0.67531
df_sin is not equal to df_cos
value of x = 0.83041	Sin x value is: 0.63657	 Cos x value : 0.67458
df_sin is not equal to df_cos
value of x = 0.83141	Sin x value is: 0.63580	 Cos x value : 0.67384
df_sin is not equal to df_cos
value of x = 0.83241	Sin x value is: 0.63503	 Cos x value : 0.67310
df_sin is not equal to df_cos
value of x = 0.83341	Sin x value is: 0.63426	 Cos x value : 0.67236
df_sin is not equal to df_cos
value of x = 0.83441	Sin x value is: 0.63348	 Cos x value : 0.67162
df_sin is not equal to df_cos
value of x = 0.83541	Sin x value is: 0.63271	 Cos x value : 0.67088
df_sin is not equal to df_cos
value of x = 0.83641	Sin x value is: 0.63194	 Cos x value : 0.67013
df_sin is not equal to df_cos
value of x = 0.83741	Sin x value is: 0.63116	 Cos x value : 0.66939
df_sin is not equal to df_cos
value of x = 0.83841	Sin x value is: 0.63039	 Cos x value : 0.66865
df_sin is not equal to df_cos
value of x = 0.83941	Sin x value is: 0.62961	 Cos x value : 0.66790
df_sin is not equal to df_cos
value of x = 0.84041	Sin x value is: 0.62883	 Cos x value : 0.66716
df_sin is not equal to df_cos
value of x = 0.84141	Sin x value is: 0.62806	 Cos x value : 0.66641
df_sin is not equal to df_cos
value of x = 0.84241	Sin x value is: 0.62728	 Cos x value : 0.66567
df_sin is not equal to df_cos
value of x = 0.84341	Sin x value is: 0.62650	 Cos x value : 0.66492
df_sin is not equal to df_cos
value of x = 0.84441	Sin x value is: 0.62572	 Cos x value : 0.66417
df_sin is not equal to df_cos